name: generate-releases

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate:
    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v1
      - run: task docs:releases
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v4
        with:
          commit_message: "chore: docs releases json auto-update"
          branch: main
          commit_user_name: actions-user
          commit_user_email: actions@github.com
          commit_author: actions-user <actions@github.com>
