on:
  push:
    branches:
      - main

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: go


  update-contributors:
    runs-on: ubuntu-latest
    name: Contribute List
    steps:
      - name: contributors-readme
        uses: akhilmhdh/contributors-readme-action@master
        id: contrib-readme
        with:
          readme_path: "CONTRIBUTORS.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
